SELECT TABLE_NAME ,COLUMN_NAME,  DATA_TYPE, CONSTRAINT_TYPE , CONSTRAINT_NAME
from user_cons_columns NATURAL JOIN ALL_CONSTRAINTS NATURAL JOIN all_tab_columns
WHERE OWNER = 'ISIS2304A431810'
ORDER BY TABLE_NAME, COLUMN_NAME;