CREATE INDEX indiceFechasReserva ON RESERVAS(FECHA_INICIO,FECHA_FIN);
CREATE INDEX indiceIdAlojamiento ON RESERVAS (ID_ALOJAMIENTO);

CREATE INDEX indiceNumPersonas ON RESERVAS(NUM_PERSONAS);
CREATE INDEX indiceCapacidadAlo ON ALOJAMIENTOS (CAPACIDAD);

CREATE INDEX indiceCosto ON RESERVAS(COSTO_DEFINITIVO);
CREATE INDEX indiceTipoHab ON HABITACIONES_HOTEL(TIPO_HABITACION);

DROP INDEX indiceFechasReserva;
DROP INDEX indiceIdAlojamiento;
DROP INDEX indiceNumPersonas;
DROP INDEX indiceCapacidadAlo;
DROP INDEX indiceCosto;
DROP INDEX indiceTipoHab;