--------------------------------------
-----------------RFC1-----------------
--------------------------------------
----Anho ACTUAL
----NOTAA:LA SEGUNDA FECHA NO ES LA FECHA ACTUAL PORQUE SI SE HIZO UNA CANCELACION Y EL TIEMPO OPORTUNO ERA HACE 1 MES, NO APARECERIA
SELECT OPE.ID,OPE.NOMBRE, SUM(RE.COSTO_DEFINITIVO)
FROM RESERVAS RE
INNER JOIN ALOJAMIENTOS ALO
ON ALO.ID=RE.ID_ALOJAMIENTO
INNER JOIN OPERADORES OPE
ON  ALO.ID_OPERADOR=OPE.ID
WHERE RE.FECHA_FIN BETWEEN '01/10/18' AND '31/12/18' AND  RE.TERMINADA='T'
GROUP BY OPE.ID, OPE.NOMBRE;



-----Anho ANTERIOR
SELECT OPE.ID,OPE.NOMBRE, SUM(RE.COSTO_DEFINITIVO) AS DINERO_RECIBIDO
FROM RESERVAS RE
INNER JOIN ALOJAMIENTOS ALO
ON ALO.ID=RE.ID_ALOJAMIENTO
INNER JOIN OPERADORES OPE
ON  ALO.ID_OPERADOR=OPE.ID
WHERE RE.FECHA_FIN BETWEEN '01/10/17' AND '31/12/17' AND  RE.TERMINADA='T'
GROUP BY OPE.ID, OPE.NOMBRE;


--------------------------------------
-----------------RFC2-----------------
--------------------------------------
---esta entregando aquellos alojamientos que han sido reservados mayor numero de veces.
SELECT A.*
FROM (SELECT ALO.ID as id_alojamiento,OPE.NOMBRE AS OPERADOR,ALO.UBICACION AS UBICACION ,COUNT(RE.ID) AS mas_reservado
FROM (RESERVAS RE
INNER JOIN ALOJAMIENTOS ALO
ON RE.ID_ALOJAMIENTO=ALO.ID
INNER JOIN OPERADORES OPE
ON ALO.ID_OPERADOR=OPE.ID)
GROUP BY ALO.ID,ALO.UBICACION, OPE.NOMBRE
ORDER BY COUNT(RE.ID) DESC) A
WHERE ROWNUM<20;



--------------------------------------
-----------------RFC3-----------------
--------------------------------------

---NORMALMENTE NO FUNCIONA NI UN POQUITO SIN LAS REGLAS DE NEGOCIO IMPLEMENTADAS:
----VERIFICAR QUE NO SE SOLAPEN RESERVAS.
----VERIFICAR QUE EL NUMERO DE PERSONAS NO SOBREPASE LA CAPACIDAD

SELECT OPE.ID, OPE.NOMBRE, SUM(RE.NUM_PERSONAS)/SUM(ALO.CAPACIDAD) AS PORCENTAJE_OCUPACION
FROM OPERADORES OPE
INNER JOIN ALOJAMIENTOS ALO
ON OPE.ID=ALO.ID_OPERADOR
INNER JOIN RESERVAS RE
ON RE.ID_ALOJAMIENTO= ALO.ID
WHERE RE.CANCELADA='F' AND 
'21/03/18' BETWEEN RE.FECHA_INICIO AND RE.FECHA_FIN
GROUP BY OPE.ID,OPE.NOMBRE;

---SIENDO 21/03/18 LA FECHA ACTUAL



--------------------------------------
-----------------RFC4-----------------
--------------------------------------
SELECT *
FROM ALOJAMIENTOS ALO
WHERE ALO.ID NOT IN 
(
SELECT RE.ID_ALOJAMIENTO
FROM  RESERVAS RE
WHERE( RE.FECHA_INICIO  BETWEEN '20/10/18' AND '30/10/18')
OR  ( RE.FECHA_FIN  BETWEEN '20/10/18' AND '30/10/18')
OR (  RE.FECHA_INICIO <'20/10/18'  AND   RE.FECHA_FIN>  '30/10/18')
)
AND ALO.ID IN
(
SELECT SEO.ID_ALOJAMIENTO
FROM  SERVICIOS_OFRECIDOS SEO
INNER JOIN  SERVICIOS SE
ON SE.ID=SEO.ID_SERVICIO
WHERE SE.NOMBRE='wi-fi'OR SE.NOMBRE='wi-fi' OR SE.NOMBRE='wi-fi'---SE CAMBIAN LOS NOMBRES.
);
--------------------------------------
-----------------RFC5-----------------
--------------------------------------

SELECT RELA.TIPO,ALO.TIPO AS TIPO_ALOJAMIENTO,SUM(RE.COSTO_DEFINITIVO) AS DINERO_PAGADO,SUM(RE.NUM_DIAS) AS DIAS_CONTRATADOS
FROM CLIENTES CLI
INNER JOIN  RESERVAS RE
ON RE.ID_CLIENTE=CLI.ID
INNER JOIN ALOJAMIENTOS ALO
ON ALO.ID=RE.ID_ALOJAMIENTO
INNER JOIN RELACIONES RELA
ON RELA.ID=CLI.ID_RELACION

GROUP BY RELA.TIPO,ALO.TIPO;

--------------------------------------
-----------------RFC6-----------------
--------------------------------------
SELECT CLI.ID,  CLI.NOMBRE,ALO.TIPO AS TIPO_ALOJAMIENTO,SUM(RE.COSTO_DEFINITIVO) AS DINERO_PAGADO,SUM(RE.NUM_DIAS) AS DIAS_CONTRATADOS
FROM CLIENTES CLI
INNER JOIN  RESERVAS RE
ON RE.ID_CLIENTE=CLI.ID
INNER JOIN ALOJAMIENTOS ALO
ON ALO.ID=RE.ID_ALOJAMIENTO
WHERE CLI.NOMBRE='EL DT'
GROUP BY CLI.NOMBRE,CLI.ID,ALO.TIPO;


--------------------------------------
-----------------RF7-----------------
--------------------------------------
SELECT *

FROM ALOJAMIENTOS ALO

WHERE ALO.ID NOT IN 

(

SELECT RE.ID_ALOJAMIENTO

FROM  RESERVAS RE

WHERE( RE.FECHA_INICIO  BETWEEN '20/10/18' AND '30/10/18')

OR  ( RE.FECHA_FIN  BETWEEN '20/10/18' AND '30/10/18')

OR (  RE.FECHA_INICIO <'20/10/18'  AND   RE.FECHA_FIN >  '30/10/18')

)

AND ALO.ID IN

(

SELECT ALOJA.ID

FROM  ALOJAMIENTOS ALOJA

WHERE ALOJA.TIPO='HAB HOTEL'

);

-----------------addReserva-----------------
