--------------------------------------
-----------------RFC1-----------------
--------------------------------------
----Anho ACTUAL
----NOTAA:LA SEGUNDA FECHA NO ES LA FECHA ACTUAL PORQUE SI SE HIZO UNA CANCELACION Y EL TIEMPO OPORTUNO ERA HACE 1 MES, NO APARECERIA
SELECT OPE.ID,OPE.NOMBRE, SUM(RE.COSTO_DEFINITIVO)
FROM RESERVAS RE
INNER JOIN ALOJAMIENTOS ALO
ON ALO.ID=RE.ID_ALOJAMIENTO
INNER JOIN OPERADORES OPE
ON  ALO.ID_OPERADOR=OPE.ID
WHERE RE.FECHA_FIN BETWEEN '01/10/18' AND '31/12/18' AND  RE.TERMINADA='T'
GROUP BY OPE.ID, OPE.NOMBRE;



-----Anho ANTERIOR
SELECT OPE.ID,OPE.NOMBRE, SUM(RE.COSTO_DEFINITIVO) AS DINERO_RECIBIDO
FROM RESERVAS RE
INNER JOIN ALOJAMIENTOS ALO
ON ALO.ID=RE.ID_ALOJAMIENTO
INNER JOIN OPERADORES OPE
ON  ALO.ID_OPERADOR=OPE.ID
WHERE RE.FECHA_FIN BETWEEN '01/10/17' AND '31/12/17' AND  RE.TERMINADA='T'
GROUP BY OPE.ID, OPE.NOMBRE;


--------------------------------------
-----------------RFC2-----------------
--------------------------------------
---esta entregando aquellos alojamientos que han sido reservados mayor numero de veces.
SELECT A.*
FROM (SELECT ALO.ID as id_alojamiento,OPE.NOMBRE AS OPERADOR,ALO.UBICACION AS UBICACION ,COUNT(RE.ID) AS mas_reservado
FROM (RESERVAS RE
INNER JOIN ALOJAMIENTOS ALO
ON RE.ID_ALOJAMIENTO=ALO.ID
INNER JOIN OPERADORES OPE
ON ALO.ID_OPERADOR=OPE.ID)
GROUP BY ALO.ID,ALO.UBICACION, OPE.NOMBRE
ORDER BY COUNT(RE.ID) DESC) A
WHERE ROWNUM<20;



--------------------------------------
-----------------RFC3-----------------
--------------------------------------

---NORMALMENTE NO FUNCIONA NI UN POQUITO SIN LAS REGLAS DE NEGOCIO IMPLEMENTADAS:
----VERIFICAR QUE NO SE SOLAPEN RESERVAS.
----VERIFICAR QUE EL NUMERO DE PERSONAS NO SOBREPASE LA CAPACIDAD

SELECT OPE.ID, OPE.NOMBRE, SUM(RE.NUM_PERSONAS)/SUM(ALO.CAPACIDAD) AS PORCENTAJE_OCUPACION
FROM OPERADORES OPE
INNER JOIN ALOJAMIENTOS ALO
ON OPE.ID=ALO.ID_OPERADOR
INNER JOIN RESERVAS RE
ON RE.ID_ALOJAMIENTO= ALO.ID
WHERE RE.CANCELADA='F' AND 
'21/03/18' BETWEEN RE.FECHA_INICIO AND RE.FECHA_FIN
GROUP BY OPE.ID,OPE.NOMBRE;

---SIENDO 21/03/18 LA FECHA ACTUAL



--------------------------------------
-----------------RFC4-----------------
--------------------------------------
SELECT *
FROM ALOJAMIENTOS ALO
WHERE ALO.ID NOT IN 
(
SELECT RE.ID_ALOJAMIENTO
FROM  RESERVAS RE
WHERE( RE.FECHA_INICIO  BETWEEN '20/10/18' AND '30/10/18')
OR  ( RE.FECHA_FIN  BETWEEN '20/10/18' AND '30/10/18')
OR (  RE.FECHA_INICIO <'20/10/18'  AND   RE.FECHA_FIN>  '30/10/18')
)
AND ALO.ID IN
(
SELECT SEO.ID_ALOJAMIENTO
FROM  SERVICIOS_OFRECIDOS SEO
INNER JOIN  SERVICIOS SE
ON SE.ID=SEO.ID_SERVICIO
WHERE SE.NOMBRE='wi-fi'OR SE.NOMBRE='wi-fi' OR SE.NOMBRE='wi-fi'---SE CAMBIAN LOS NOMBRES.
);
--------------------------------------
-----------------RFC5-----------------
--------------------------------------

SELECT RELA.TIPO,ALO.TIPO AS TIPO_ALOJAMIENTO,SUM(RE.COSTO_DEFINITIVO) AS DINERO_PAGADO,SUM(RE.NUM_DIAS) AS DIAS_CONTRATADOS
FROM CLIENTES CLI
INNER JOIN  RESERVAS RE
ON RE.ID_CLIENTE=CLI.ID
INNER JOIN ALOJAMIENTOS ALO
ON ALO.ID=RE.ID_ALOJAMIENTO
INNER JOIN RELACIONES RELA
ON RELA.ID=CLI.ID_RELACION

GROUP BY RELA.TIPO,ALO.TIPO;

--------------------------------------
-----------------RFC6-----------------
--------------------------------------
SELECT CLI.ID,  CLI.NOMBRE,ALO.TIPO AS TIPO_ALOJAMIENTO,SUM(RE.COSTO_DEFINITIVO) AS DINERO_PAGADO,SUM(RE.NUM_DIAS) AS DIAS_CONTRATADOS
FROM CLIENTES CLI
INNER JOIN  RESERVAS RE
ON RE.ID_CLIENTE=CLI.ID
INNER JOIN ALOJAMIENTOS ALO
ON ALO.ID=RE.ID_ALOJAMIENTO
WHERE CLI.NOMBRE='EL DT'
GROUP BY CLI.NOMBRE,CLI.ID,ALO.TIPO;
--------------------------------------
-----------------RFC10-----------------
--------------------------------------
RFC10 - CONSULTAR CONSUMO EN ALOHANDES

SELECT * FROM CLIENTES CLIEN WHERE CLIEN.ID IN (
    SELECT RESERV.ID_CLIENTE FROM RESERVAS RESERV WHERE
    
        (( RESERV.FECHA_INICIO  BETWEEN '20/10/18' AND '30/10/18')

        OR  ( RESERV.FECHA_FIN  BETWEEN '20/10/18' AND '30/10/18')

        OR (  RESERV.FECHA_INICIO <'20/10/18'  AND   RESERV.FECHA_FIN >  '30/10/18')

        ) AND RESERV.ID_ALOJAMIENTO = 2 ) 
--------Menos eficiencia--------------
    ORDER BY CLIEN.NOMBRE; 
    
    
--------------------------------------
-----------------RFC11-----------------
--------------------------------------

   SELECT * FROM CLIENTES CLIEN WHERE CLIEN.ID  NOT IN (
    SELECT RESERV.ID_CLIENTE FROM RESERVAS RESERV WHERE
    
        (( RESERV.FECHA_INICIO  BETWEEN '20/10/18' AND '30/10/18')

        OR  ( RESERV.FECHA_FIN  BETWEEN '20/10/18' AND '30/10/18')

        OR (  RESERV.FECHA_INICIO <'20/10/18'  AND   RESERV.FECHA_FIN >  '30/10/18')

        ) AND RESERV.ID_ALOJAMIENTO = 2 ) 
        --------Menos eficiencia--------------
    ORDER BY CLIEN.NOMBRE; 
--------------------------------------
-----------------RFC12-----------------
--------------------------------------


WITH Q1 AS
(SELECT ALO.ID AS ALOID ,RES.NUM_PERSONAS/ALO.CAPACIDAD AS CAPACI,TO_CHAR(RES.FECHA_INICIO,'IW')AS SEMA
FROM ALOJAMIENTOS ALO
INNER JOIN RESERVAS RES
ON ALO.ID=RES.ID_ALOJAMIENTO
WHERE EXTRACT( YEAR FROM FECHA_INICIO) = 2018),

Q2 AS
(SELECT MAX(RESE.NUM_PERSONAS/ALOJ.CAPACIDAD) AS CAPACIMAX, TO_CHAR(RESE.FECHA_INICIO,'IW') AS SEMA, MIN(RESE.NUM_PERSONAS/ALOJ.CAPACIDAD) AS CAPACIMIN
FROM ALOJAMIENTOS ALOJ
INNER JOIN RESERVAS RESE
ON ALOJ.ID=RESE.ID_ALOJAMIENTO
GROUP BY EXTRACT( YEAR FROM FECHA_INICIO), TO_CHAR(RESE.FECHA_INICIO,'IW')
HAVING EXTRACT( YEAR FROM FECHA_INICIO) = 2018),

Q3 AS
(SELECT Q1.SEMA AS SEMANA, Q1.ALOID AS ALOJAMIENTOMAX, Q2.CAPACIMAX AS OCUPACIONMAX, Q2.CAPACIMIN AS OCUPACIONMIN
FROM Q1 
INNER JOIN Q2
ON  Q1.SEMA=Q2.SEMA AND Q1.CAPACI=Q2.CAPACIMAX),

Q4 AS(
SELECT Q3.SEMANA, Q3.ALOJAMIENTOMAX, Q3.OCUPACIONMAX, Q1.ALOID AS ALOJAMIENTOMIN, Q3.OCUPACIONMIN
FROM Q1 INNER JOIN Q3
ON  Q1.SEMA=Q3.SEMANA AND Q1.CAPACI=Q3.OCUPACIONMIN),

R1 AS
(SELECT SEM, MAX(SOLICI) AS MAXIM, MIN (SOLICI)AS MINIM
FROM
(SELECT tabla1.SEMANA AS SEM, ALOJAMIENTOS.ID_OPERADOR, SUM(tabla1.CUENTA) AS SOLICI
FROM(SELECT TO_CHAR(FECHA_INICIO,'IW')AS SEMANA,ID_ALOJAMIENTO AS ALOJ,  COUNT (ID) AS CUENTA
FROM RESERVAS
GROUP BY EXTRACT( YEAR FROM FECHA_INICIO), TO_CHAR(FECHA_INICIO,'IW'), ID_ALOJAMIENTO
HAVING EXTRACT( YEAR FROM FECHA_INICIO) = 2018 )tabla1 inner join ALOJAMIENTOS
ON tabla1.ALOJ = ALOJAMIENTOS.ID
GROUP BY tabla1.SEMANA,ALOJAMIENTOS.ID_OPERADOR)
GROUP BY SEM ),
R2 AS 
(SELECT tabla1.SEMANA2 AS SEM2, ALOJAMIENTOS.ID_OPERADOR AS OPER, SUM(tabla1.CUENTA2) AS SOLICI2
FROM(SELECT TO_CHAR(FECHA_INICIO,'IW')AS SEMANA2,ID_ALOJAMIENTO AS ALOJ2,  COUNT (ID) AS CUENTA2
FROM RESERVAS
GROUP BY EXTRACT( YEAR FROM FECHA_INICIO), TO_CHAR(FECHA_INICIO,'IW'), ID_ALOJAMIENTO
HAVING EXTRACT( YEAR FROM FECHA_INICIO) = 2018 )tabla1 inner join ALOJAMIENTOS
ON tabla1.ALOJ2 = ALOJAMIENTOS.ID
GROUP BY tabla1.SEMANA2,ALOJAMIENTOS.ID_OPERADOR),
R3 AS (
SELECT R1.SEM , R1.MAXIM, R1.MINIM, R2.OPER
FROM R1 INNER JOIN R2
ON R1.SEM = R2.SEM2 AND  R1.MAXIM = R2.SOLICI2),
R4 AS (
SELECT  R3.SEM AS SEMANA1, R3.OPER AS OPERADORMAX, R3.MAXIM AS MAXIM, R2.OPER AS OPERADORMIN, R3.MINIM AS MINIM
FROM R3 INNER JOIN R2
ON R3.SEM = R2.SEM2 AND  R3.MINIM = R2.SOLICI2
ORDER BY R3.SEM)
SELECT Q4.SEMANA ,Q4.ALOJAMIENTOMAX, Q4.OCUPACIONMAX, Q4.ALOJAMIENTOMIN, Q4.OCUPACIONMIN, R4.OPERADORMAX , R4.MAXIM , R4.OPERADORMIN, R4.MINIM
FROM Q4 INNER JOIN R4
ON Q4.SEMANA = R4.SEMANA1
 --------Menos eficiencia--------------
ORDER BY Q4.SEMANA
--------------------------------------
-----------------RFC12 Alternativa ---
--------------------------------------
WITH R1 AS (SELECT SEM, MAX(SOLICI) AS MAXIM, MIN (SOLICI)AS MINIM FROM (SELECT tabla1.SEMANA AS SEM, ALOJAMIENTOS.ID_OPERADOR, SUM(tabla1.CUENTA) AS SOLICI FROM(SELECT TO_CHAR(FECHA_INICIO,'IW')AS SEMANA,ID_ALOJAMIENTO AS ALOJ,  COUNT (ID) AS CUENTA FROM RESERVAS GROUP BY EXTRACT( YEAR FROM FECHA_INICIO), TO_CHAR(FECHA_INICIO,'IW'), ID_ALOJAMIENTO HAVING EXTRACT( YEAR FROM FECHA_INICIO) = 2018 )tabla1 inner join ALOJAMIENTOS ON tabla1.ALOJ = ALOJAMIENTOS.ID GROUP BY tabla1.SEMANA,ALOJAMIENTOS.ID_OPERADOR) GROUP BY SEM ),
R2 AS (SELECT tabla1.SEMANA2 AS SEM2, ALOJAMIENTOS.ID_OPERADOR AS OPER, SUM(tabla1.CUENTA2) AS SOLICI2 FROM(SELECT TO_CHAR(FECHA_INICIO,'IW')AS SEMANA2,ID_ALOJAMIENTO AS ALOJ2,  COUNT (ID) AS CUENTA2 FROM RESERVAS GROUP BY EXTRACT( YEAR FROM FECHA_INICIO), TO_CHAR(FECHA_INICIO,'IW'), ID_ALOJAMIENTO HAVING EXTRACT( YEAR FROM FECHA_INICIO) = 2018 )tabla1 inner join ALOJAMIENTOS ON tabla1.ALOJ2 = ALOJAMIENTOS.ID GROUP BY tabla1.SEMANA2,ALOJAMIENTOS.ID_OPERADOR),
R3 AS ( SELECT R1.SEM , R1.MAXIM, R1.MINIM, R2.OPER FROM R1 INNER JOIN R2 ON R1.SEM = R2.SEM2 AND  R1.MAXIM = R2.SOLICI2)
SELECT  R3.SEM AS SEMANA , R3.OPER AS OPERADORMAX, R3.MAXIM, R2.OPER AS OPERADORMIN, R3.MINIM FROM R3 INNER JOIN R2 ON R3.SEM = R2.SEM2 AND  R3.MINIM = R2.SOLICI2;

WITH Q1 AS (SELECT ALO.ID AS ALOID ,RES.NUM_PERSONAS/ALO.CAPACIDAD AS CAPACI,TO_CHAR(RES.FECHA_INICIO,'IW')AS SEMA FROM ALOJAMIENTOS ALO INNER JOIN RESERVAS RES ON ALO.ID=RES.ID_ALOJAMIENTO WHERE EXTRACT( YEAR FROM FECHA_INICIO) = 2018), 
Q2 AS (SELECT MAX(RESE.NUM_PERSONAS/ALOJ.CAPACIDAD) AS CAPACIMAX, TO_CHAR(RESE.FECHA_INICIO,'IW') AS SEMA, MIN(RESE.NUM_PERSONAS/ALOJ.CAPACIDAD) AS CAPACIMIN FROM ALOJAMIENTOS ALOJ INNER JOIN RESERVAS RESE ON ALOJ.ID=RESE.ID_ALOJAMIENTO GROUP BY EXTRACT( YEAR FROM FECHA_INICIO), TO_CHAR(RESE.FECHA_INICIO,'IW') HAVING EXTRACT( YEAR FROM FECHA_INICIO) = 2018),
Q3 AS (SELECT Q1.SEMA AS SEMANA, Q1.ALOID AS ALOJAMIENTOMAX, Q2.CAPACIMAX AS OCUPACIONMAX, Q2.CAPACIMIN AS OCUPACIONMIN FROM Q1  INNER JOIN Q2 ON  Q1.SEMA=Q2.SEMA AND Q1.CAPACI=Q2.CAPACIMAX)
SELECT Q3.SEMANA, Q3.ALOJAMIENTOMAX, Q3.OCUPACIONMAX, Q1.ALOID AS ALOJAMIENTOMIN, Q3.OCUPACIONMIN FROM Q1 INNER JOIN Q3 ON  Q1.SEMA=Q3.SEMANA AND Q1.CAPACI=Q3.OCUPACIONMIN;

--------------------------------------
-----------------RFC13-----------------
--------------------------------------

WITH Q1 AS(
SELECT CLI.ID AS IDQ1, MIN(RESV.COSTO_DEFINITIVO/(TRUNC (RESV.FECHA_FIN) - TRUNC (RESV.FECHA_INICIO))) AS RAZONQ1
FROM CLIENTES CLI
INNER JOIN RESERVAS RESV
ON CLI.ID=RESV.ID_CLIENTE
WHERE CLI.ID NOT IN
(SELECT ID_CLIENTE 
FROM RESERVAS RESI
WHERE (RESI.COSTO_DEFINITIVO/(TRUNC (RESI.FECHA_FIN) - TRUNC (RESI.FECHA_INICIO)))<125)
GROUP BY CLI.ID ),
Q2 AS (
SELECT CLI.ID AS IDQ2 , COUNT (RES1.ID) AS RAZONQ2
FROM ((CLIENTES CLI
INNER JOIN RESERVAS RES1
ON  RES1.ID_CLIENTE=CLI.ID)
INNER JOIN HABITACIONES_HOTEL HOT 
ON HOT.ID=RES1.ID_ALOJAMIENTO)
WHERE CLI.ID NOT IN
(SELECT RESER1.ID_CLIENTE
FROM RESERVAS  RESER1
INNER JOIN HABITACIONES_HOTEL HO
ON HO.ID=RESER1.ID_ALOJAMIENTO
WHERE HO.TIPO_HABITACION != 'SUITE')
AND CLI.ID NOT IN(
SELECT RESER2.ID_CLIENTE
FROM RESERVAS  RESER2
INNER JOIN  ALOJAMIENTOS ALOJ
ON ALOJ.ID=RESER2.ID_ALOJAMIENTO
WHERE ALOJ.TIPO != 'HAB HOTEL'
)
AND  CLI.ID IN(
SELECT RES.ID_CLIENTE
FROM RESERVAS RES
)
GROUP BY CLI.ID),
Q3 AS (
SELECT  RES.ID_CLIENTE AS IDQ3,COUNT(DISTINCT(TO_CHAR(RES.FECHA_INICIO,'MM'))*(TO_CHAR(RES.FECHA_INICIO,'YY'))) AS RAZONQ3
FROM RESERVAS RES
GROUP BY RES.ID_CLIENTE
HAVING COUNT(DISTINCT(TO_CHAR(RES.FECHA_INICIO,'MM'))*(TO_CHAR(RES.FECHA_INICIO,'YY'))) >= ( SELECT COUNT(*) FROM (SELECT  DISTINCT TO_CHAR(FECHA_INICIO,'YY'),TO_CHAR(FECHA_INICIO,'MM') FROM RESERVAS))),
Q4 AS (
SELECT Q1.IDQ1, Q1.RAZONQ1, Q2.IDQ2, Q2.RAZONQ2
FROM Q1 FULL OUTER JOIN Q2
ON Q1.IDQ1 = Q2.IDQ2)
SELECT Q4.IDQ1, Q4.RAZONQ1, Q4.IDQ2, Q4.RAZONQ2, Q3.IDQ3, Q3.RAZONQ3
FROM Q4 FULL OUTER JOIN Q3
ON Q4.IDQ1 = Q3.IDQ3;
--------------------------------------
-----------------RF7-----------------
--------------------------------------
SELECT *

FROM ALOJAMIENTOS ALO

WHERE ALO.ID NOT IN 

(

SELECT RE.ID_ALOJAMIENTO

FROM  RESERVAS RE

WHERE( RE.FECHA_INICIO  BETWEEN '20/10/18' AND '30/10/18')

OR  ( RE.FECHA_FIN  BETWEEN '20/10/18' AND '30/10/18')

OR (  RE.FECHA_INICIO <'20/10/18'  AND   RE.FECHA_FIN >  '30/10/18')

)

AND ALO.ID IN

(

SELECT ALOJA.ID

FROM  ALOJAMIENTOS ALOJA

WHERE ALOJA.TIPO='HAB HOTEL'

);

-----------------addReserva-----------------
